#ifndef KTK_Enum_h__
#define KTK_Enum_h__

enum class Stage {
	NONE, READY, JUDGE, DRAWCARD, PLAYCARD, DISCARD, ROUNDEND
};

enum class Slash_State {
	WEAPONCHECKBEFORESLASH, ARMORCHECKBEFORESLASH, SLASHING, SLASHSUCCESS, SLASHFAIL, HURTING, SLASHFINISH
};

enum class Skill_State {
	CANTUSE, CANUSE, USING
};

enum class PlayerPanalState {
	SELECTED, CANSELECTED, CANTSELECTED
};

enum class Player_Color {
	BULE, RED, YELLOW, DARK
};

enum class Horse_Type {
	NONE, DEFENSIVE, OFFENSIVE
};

enum class Event_Type {
	REQUEST_CARD
};

enum class Event_State {
	START, HUMAN_RESPONSING, AI_RESPONSING, FINISH
};

enum class EquipmentPanalState {
	SELECTED, CANSELECTED, CANTSELECTED
};

enum class EquipmentCard_Type {
	NONE, WEAPON, ARMOR, HORSE
};

enum class Char_SkillType {
	NONE, ACTIVESKILL, MANDATORYSKILL
};

enum class Char_SkillName {
	NONE, JIANXIONG, HUJIA, TIANDU, YIJI, FANKUI, GUICAI, GANGLIE, LUOYI, TUXI, QINGGUO, RENDE, JIJIANG, WUSHENG, PAOXIAO, GUANXING, KONGCHENG, LONGDAN, JIZHI, QICAI, KEJI, MASHU, TIEJI, ZHIHENG, JIUYUAN, YINGZI, FANJIAN, GUOSE, LIULI, JIEYIN, XIAOJI, QIXI, KUROU, QIANXUN, LIANYING, LIJIAN, BIYUE, WUSHUANG, JIJIU, QINGNANG
};

enum class Char_Sex {
	NONE, FEMALE, MALE
};

enum class Char_Name {
	NONE, CAOCAO, DAQIAO, DIAOCHAN, GANNING, GUANYU, GUOJIA, HUANGGAI, HUANGYUEYING, HUATUO, LIUBEI, LUXUN, LVBU, LVMENG, MACHAO, SIMAYI, SUNSHANGXIANG, XIAHOUDUN, XUNQUAN, XUZHU, ZHANGFEI, ZHANGLIAO, ZHAOYUN, ZHENJI, ZHOUYU, ZHUGELIANG
};

enum class Char_ID {
	NONE, INSURGENT, LORD, MINISTER, SPY
};

enum class Char_Force {
	WEI, SHU, WU, QUN, NONE
};

enum class CardPile_Type {
	NONE, DARKCARD, DISCARD, HANDCARD
};

enum class Card_Type {
	NONE, BASIC, DELAYEDSTRATEGY, EQUIPMENT, STRATEGY
};

enum class Card_Suit {
	NONE, CLUB, DIAMOND, HEART, SPADE
};

enum class Card_Name {
	NONE, ALLOUTOFNONE, ARROWRAIN, BAGUARANK, COUPLESWORDS, DODGE, DRAGONBROADSWORD, DROWNLNHAPPINESS, DUEL, FLAWLESSDEFENSE, GUANSHIAXE, HARVEST, ICESWORD, JUSTICESHIELD, KYLINBOW, LIGHTNING, MURDERWITHBORROWEDWEAPON, OATHLNPEACHGARDEN, PEACH, SABOTAGE, SLASH, SNAKESPEAR, SOUTHLNVASION, THEFT, TRIPLEHALBERD, TSINGGANGSWORD, ZHUGECROSSBOW, JUEYING, ZHUAHUANGFEIDIAN, DILU, ZIXING, CHITU, DAWAN
};

enum class Card_Color {
	NONE, BLACK, RED
};

#endif // KTK_Enum_h__
